management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
#  security:
#    user:
#      name: roman
#      password: roman
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: create-drop
      default_schema: public
    open-in-view: false